apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 2s
      evaluation_interval: 2s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'Microservice1'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['host.docker.internal:9989']
      - job_name: 'Microservice2'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['host.docker.internal:9988']
      - job_name: 'Microservice3'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['host.docker.internal:9987']
