# otel-collector-configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: default
data:
  otel-collector.yml: |
    receivers:
      otlp:
        protocols:
          grpc:
    exporters:
      logging:
      loki:
        endpoint: "http://loki:3100/loki/api/v1/push"
    service:
      pipelines:
        logs:
          receivers: [otlp]
          exporters: [logging, loki]
