#receivers:
#  otlp:
#    protocols:
#      grpc:
#
#processors:
#  batch:
#
#exporters:
#  loki:
#    endpoint: "http://loki:3100/loki/api/v1/push"
#
#service:
#  pipelines:
#    logs:
#      receivers: [otlp]
#      exporters: [loki]
receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [logging, loki]

