global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'Microservice1'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9989']
  - job_name: 'Microservice2'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9988']
  - job_name: 'Microservice3'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9987']